name: Docker image release

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build and push new image
    runs-on: ubuntu-latest
    steps:
      - name: Get commit hash
        id: sha
        run: echo "::set-output name=sha::${GITHUB_SHA::7}"

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push new image
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: "Dockerfile"
          tags: |
            ghcr.io/lyarenei/plex-beetbrainz:latest
            ghcr.io/lyarenei/plex-beetbrainz:${{ steps.sha.outputs.sha }}
